services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    container_name: "redis"
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
